// ======================== Transaction Model ========================
const mongoose = require("mongoose");
const constant = require("../../constant");

const TransactionSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      required: true,
      index: true,
    },
    amount: {
      type: Number,
      required: true,
      min: [0.01, "Amount must be greater than 0"],
    },
    type: {
      type: String,
      enum: constant.TRANSACTION_TYPES,
      required: true,
      index: true,
    },
    category: {
      type: String,
      required: true,
      trim: true,
    },
    date: {
      type: Date,
      required: true,
      index: true,
    },
    note: {
      type: String,
      default: "",
      trim: true,
      maxlength: 500,
    },
    receipt: {
      type: String, // URL or base64
      default: null,
    },
    currency: {
      type: String,
      default: "INR",
    },
    isDeleted: {
      type: Boolean,
      default: false,
      index: true,
    },
    syncId: {
      type: String, // Unique ID generated by mobile app
      index: true,
      unique: true,
      sparse: true,
    },
  },
  { timestamps: true }
);

// Compound index for analytics queries
TransactionSchema.index({ userId: 1, date: -1 });
TransactionSchema.index({ userId: 1, type: 1, date: -1 });

module.exports = mongoose.model(constant.DB_MODEL_REF.TRANSACTION, TransactionSchema);
