// ======================== Goal Model ========================
const mongoose = require("mongoose");
const constant = require("../../constant");

const GoalSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      required: true,
      index: true,
    },
    title: {
      type: String,
      required: true,
      trim: true,
      maxlength: 100,
    },
    description: {
      type: String,
      default: "",
      trim: true,
      maxlength: 500,
    },
    targetAmount: {
      type: Number,
      required: true,
      min: [1, "Target amount must be at least 1"],
    },
    currentAmount: {
      type: Number,
      default: 0,
      min: 0,
    },
    // Emoji or icon identifier for UI
    icon: {
      type: String,
      default: "🎯",
    },
    // Color theme for the card
    color: {
      type: String,
      default: "#6C63FF",
    },
    // Streak tracking (days met savings threshold)
    streak: {
      type: Number,
      default: 0,
      min: 0,
    },
    lastStreakUpdated: {
      type: Date,
      default: null,
    },
    // Target date (for projections)
    targetDate: {
      type: Date,
      default: null,
    },
    isCompleted: {
      type: Boolean,
      default: false,
    },
    isDeleted: {
      type: Boolean,
      default: false,
      index: true,
    },
    priority: {
      type: Number,
      default: 1, // 1 = highest
      min: 1,
    },
    syncId: {
      type: String, // Unique ID generated by mobile app
      index: true,
      unique: true,
      sparse: true,
    },
  },
  { timestamps: true }
);

GoalSchema.index({ userId: 1, isDeleted: 1 });

module.exports = mongoose.model(constant.DB_MODEL_REF.GOAL, GoalSchema);
